// <auto-generated />
using System;
using GTUParser.Remote;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GTUParser.Migrations
{
    [DbContext(typeof(GTUDbContext))]
    [Migration("20230603143806_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GTUParser.Models.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPractice")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LectureDay")
                        .HasColumnType("int");

                    b.Property<string>("LectureName")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .HasColumnType("longtext");

                    b.Property<ushort>("TimeId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("ZoomId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("GTUParser.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("GTUParser.Models.Lecture", b =>
                {
                    b.HasOne("GTUParser.Models.Table", null)
                        .WithMany("Lectures")
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("GTUParser.Models.Table", b =>
                {
                    b.Navigation("Lectures");
                });
#pragma warning restore 612, 618
        }
    }
}
